# -*- coding: utf-8 -*-
"""Cópia de Workshop_API.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ivucBcKWN0KMs4dKi0emZpo2dxzQOeTO
"""

import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

caminho_in = ('/content/drive/My Drive/Dados/') # caminho especificio do arquivo antes de ser programado
caminho_out = ('/content/drive/My Drive/Dados/') # o /data é a pasta do marquinho e o /content é o caminho dele out vai sair o caminho depois programado

file1 = caminho_in + "2024Atracacao.txt"
with open (file1, 'r', encoding='UTF-8') as f:
  linhas = f.readlines()
  for i in range (0, 5):
    print(f"Linha {i+1}: {linhas[i]}")

df1 = pd.read_csv(file1, low_memory=False, sep=';', encoding = 'UTF-8', decimal =",")
df1.info()

file2 = caminho_in + '2023Atracacao.txt'
with open(file2, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

df2 = pd.read_csv(file2, low_memory=False, sep=';', encoding = 'UTF-8', decimal =",")
df2.info()

csv_final = [file1, file2]
ANTAQ_Int = pd.DataFrame()
for csv_final in csv_final:
    df = pd.read_csv(csv_final, sep = ';')
    ANTAQ_Int = pd.concat([ANTAQ_Int, df], ignore_index=True)
ANTAQ_Int.info()

ANTAQ_Int.head(5)

ANTAQ_Int.tail(5)

colunas_interesse = ['IDAtracacao','IDBerco',
                     'Data Atracação', 'Data Chegada',
                     'Data Desatracação','Data Início Operação',
                     'Data Término Operação']

ANTAQ = ANTAQ_Int.dropna(subset=colunas_interesse)
ANTAQ.info()

ANTAQ['Data Chegada'] = pd.to_datetime(ANTAQ['Data Chegada'], format='%d/%m/%Y %H:%M:%S')
ANTAQ['Data Atracação'] = pd.to_datetime(ANTAQ['Data Atracação'], format='%d/%m/%Y %H:%M:%S')
ANTAQ['Data Início Operação'] = pd.to_datetime(ANTAQ['Data Início Operação'], format='%d/%m/%Y %H:%M:%S')
ANTAQ['Data Término Operação'] = pd.to_datetime(ANTAQ['Data Término Operação'], format='%d/%m/%Y %H:%M:%S')
ANTAQ['Data Desatracação'] = pd.to_datetime(ANTAQ['Data Desatracação'], format='%d/%m/%Y %H:%M:%S')

ANTAQ['Tempo_espera_chegada'] = (ANTAQ['Data Atracação'] - ANTAQ['Data Chegada']).dt.total_seconds() / 3600
ANTAQ['Tempo_espera_inicial'] = (ANTAQ['Data Início Operação'] - ANTAQ['Data Atracação']).dt.total_seconds() / 3600
ANTAQ['Tempo_operacao'] = (ANTAQ['Data Término Operação'] - ANTAQ['Data Início Operação']).dt.total_seconds() / 3600
ANTAQ['Tempo_espera_final'] = (ANTAQ['Data Desatracação'] - ANTAQ['Data Término Operação']).dt.total_seconds() / 3600
ANTAQ['Tempo_ocupacao'] = (ANTAQ['Data Desatracação'] - ANTAQ['Data Atracação']).dt.total_seconds() / 3600

ANTAQ.info()

duplicados = ANTAQ.duplicated(subset=['IDAtracacao'], keep=False)
if duplicados.any():
    print("Existem valores duplicados.")
    print(ANTAQ[duplicados])
else:
    print("Coluna com valores unicos.")

coluna = 'Complexo Portuário'
CP = ANTAQ[coluna].value_counts().sort_index()
print(f"Total de operações por {coluna}:")
print(CP)

porto = 'Santos'
navegacao = 'Longo Curso'
filtro =  ANTAQ[(ANTAQ['Complexo Portuário'] == porto) &
                (ANTAQ['Tipo de Navegação da Atracação'] == navegacao)]
tabela = filtro.groupby('Berço').agg({'Berço': 'count'}).rename(columns={'Berço': 'Total'})
print(tabela)

filtro.info()

colunas_interesse1 = ['IDAtracacao','CDTUP','Berço','Porto Atracação', 'Complexo Portuário','Tipo de Navegação da Atracação',
                      'Data Chegada','Data Atracação','Data Início Operação','Data Término Operação','Data Desatracação',
                      'Tempo_espera_chegada', 'Tempo_espera_inicial','Tempo_operacao', 'Tempo_espera_final', 'Tempo_ocupacao']
ANTAQ[colunas_interesse1].to_csv(caminho_out + 'Atracacao_final.csv', index=False)

drive.mount('/content/drive')
arquivo = '/content/drive/My Drive/Dados/Atracacao_final.csv'
with open (arquivo, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

df = pd.read_csv(arquivo, low_memory=False, sep=',', encoding='UTF-8')
df.head()

file3 = caminho_in+'2024Carga.txt'
with open (file3, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

df2 = pd.read_csv(file3, low_memory=False, sep=';', encoding = 'UTF-8', decimal =",")
df2.info()

df2.head(5)

file4 = caminho_in+'2023Carga.txt'
with open(file3, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

csv_final = [file3, file4]
Carga_Int = pd.DataFrame()
for csv_final in csv_final:
    df = pd.read_csv(csv_final, sep=';', low_memory=False)
    Carga_Int = pd.concat([Carga_Int, df], ignore_index=True)
Carga_Int.info()

duplicados2 = Carga_Int.duplicated(subset=['IDAtracacao'], keep=False)
if duplicados2.any():
    print("Existem valores duplicados.")
else:
    print("Coluna com valores unicos.")

sentido = 'Embarcados'
navegacao = 'Longo Curso'
cargas = ['1201','1005']
operacao = 'Exclusivo'
df3 = Carga_Int[(Carga_Int['Sentido'] == sentido) &
                (Carga_Int['Tipo Navegação'] == navegacao) &
                (Carga_Int['CDMercadoria'].isin(cargas)) &
                (Carga_Int['STSH4'] == operacao)]
df3.info()

coluna = ['IDAtracacao', 'CDMercadoria', 'Sentido',]
coluna_valor = 'VLPesoCargaBruta'
cargas = df3.groupby(coluna)[coluna_valor].sum().reset_index()

cargas.head(5)

final = pd.merge(ANTAQ, cargas, left_on='IDAtracacao', right_on='IDAtracacao', how='inner')

final.info()

final.head(5)

final

final.mean(numeric_only=True)

colunas_desejadas = ['Tempo_espera_chegada', 'Tempo_espera_inicial',
                     'Tempo_operacao', 'Tempo_espera_final',
                     'Tempo_ocupacao', 'VLPesoCargaBruta']

media_selecionada = final[colunas_desejadas].mean(numeric_only=True)
pd.options.display.float_format = '{:.6f}'.format
print(media_selecionada)

import matplotlib as plt
import seaborn as sns
sns.set(style='whitegrid', palette="deep", font_scale=1.1, rc={"figure.figsize": [8, 5]})

espera_atracar = final['Tempo_espera_chegada']
espera_atracar.describe()

sns.histplot(espera_atracar)

final.to_csv(caminho_out+'Base_final_ANTAQ.csv', index=False)

file5 = caminho_in+'2024TemposAtracacao.txt'
with open (file3, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

file6 = caminho_in+'2023TemposAtracacao.txt'
with open (file3, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

file7 = caminho_in+'2024TemposAtracacaoParalisacao.txt'
with open (file3, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

file8 = caminho_in+'2023TemposAtracacaoParalisacao.txt'
with open (file3, 'r', encoding='UTF-8') as f:
    linhas = f.readlines()
    for i in range(0, 5):
        print(f"Linha {i+1}: {linhas[i]}")

csv_final = [file5, file7]
Carga_Int = pd.DataFrame()
for csv_final in csv_final:
    df = pd.read_csv(csv_final, sep=';', low_memory=False)
    Carga_Int = pd.concat([Carga_Int, df], ignore_index=True)
Carga_Int.info()

csv_final = [file6, file8]
Carga_Int = pd.DataFrame()
for csv_final in csv_final:
    df = pd.read_csv(csv_final, sep=';', low_memory=False)
    Carga_Int = pd.concat([Carga_Int, df], ignore_index=True)
Carga_Int.info()

import pandas as pd

# Lista com os arquivos
arquivos = [file5, file7]

# DataFrame para consolidar
Carga_Int = pd.DataFrame()

# Leitura e concatenação
for arquivo in arquivos:
    df = pd.read_csv(arquivo, sep=';', low_memory=False)
    Carga_Int = pd.concat([Carga_Int, df], ignore_index=True)

# Verifica se a coluna existe e trata
if 'DescricaoTempoDesconto' in Carga_Int.columns:
    # Seleciona as colunas
    df_filtrado = Carga_Int[['IDAtracacao', 'DescricaoTempoDesconto']].copy()

    # Trata valores: transforma em string e remove espaços
    df_filtrado['DescricaoTempoDesconto'] = df_filtrado['DescricaoTempoDesconto'].astype(str).str.strip()

    # Remove vazios e NaNs
    df_filtrado = df_filtrado[df_filtrado['DescricaoTempoDesconto'] != '']
    df_filtrado = df_filtrado[df_filtrado['DescricaoTempoDesconto'].str.lower() != 'nan']

    # Exporta para CSV
    df_filtrado.to_csv('saida_filtrada_2.csv', index=False, encoding='utf-8-sig')

    print("Arquivo gerado com sucesso sem nenhum NaN ou vazio 🧼✅")
else:
    print("⚠️ Coluna 'DescricaoTempoDesconto' não encontrada em um dos arquivos.")

import pandas as pd

# Lista com os arquivos
arquivos = [file6, file8]

# DataFrame para consolidar
Carga_Int = pd.DataFrame()

# Leitura e concatenação
for arquivo in arquivos:
    df = pd.read_csv(arquivo, sep=';', low_memory=False)
    Carga_Int = pd.concat([Carga_Int, df], ignore_index=True)

# Verifica se a coluna existe e trata
if 'DescricaoTempoDesconto' in Carga_Int.columns:
    # Seleciona as colunas
    df_filtrado_2 = Carga_Int[['IDAtracacao', 'DescricaoTempoDesconto']].copy()

    # Trata valores: transforma em string e remove espaços
    df_filtrado_2['DescricaoTempoDesconto'] = df_filtrado_2['DescricaoTempoDesconto'].astype(str).str.strip()

    # Remove vazios e NaNs
    df_filtrado_2 = df_filtrado_2[df_filtrado_2['DescricaoTempoDesconto'] != '']
    df_filtrado_2 = df_filtrado_2[df_filtrado_2['DescricaoTempoDesconto'].str.lower() != 'nan']

    # Exporta para CSV
    df_filtrado_2.to_csv('saida_filtrada_2.csv', index=False, encoding='utf-8-sig')

    print("Arquivo gerado com sucesso sem nenhum NaN ou vazio 🧼✅")
else:
    print("⚠️ Coluna 'DescricaoTempoDesconto' não encontrada em um dos arquivos.")

from google.colab import files
import pandas as pd

# Dicionário com seus DataFrames (substitua pelas suas variáveis reais)
dataframes_para_exportar = {
    "motivos_portos_2024": df_filtrado_2,
    "motivos_portos_2023": df_filtrado
}

# Verificação e exportação
for nome_df, df in dataframes_para_exportar.items():
    try:
        # Verifica se é um DataFrame (ou Series, que também pode ser exportada)
        if isinstance(df, (pd.DataFrame, pd.Series)):
            nome_arquivo = f"{nome_df}.csv"

            # Converte Series para DataFrame se necessário
            if isinstance(df, pd.Series):
                df = df.to_frame()

            df.to_csv(nome_arquivo, index=True, encoding='utf-8-sig')  # index=True mantém os índices
            files.download(nome_arquivo)
            print(f"✅ {nome_df} exportado como {nome_arquivo}")
        else:
            print(f"⚠️ {nome_df} não é um DataFrame/Series (tipo: {type(df)})")
    except Exception as e:
        print(f"❌ Erro ao exportar {nome_df}: {str(e)}")

print("\nTodos os arquivos exportados com sucesso!")

#CODIGO QUE TIREI DA CABEÇA

import pandas as pd

# Corrige pesos que vêm como texto com ponto e vírgula (ou só vírgula)
def converter_peso(valor):
    if isinstance(valor, str):
        valor = valor.replace('.', '').replace(',', '.')
    try:
        return float(valor)
    except:
        return None

# Aplica a conversão corretamente
for df in [Carga_Int, final]:
    if 'VLPesoCargaBruta' in df.columns:
        df['VLPesoCargaBruta'] = df['VLPesoCargaBruta'].apply(converter_peso)

# Verifique se agora os valores são realmente float
print(final['VLPesoCargaBruta'].dtypes)

produtividade = final.groupby('CDTUP')['VLPesoCargaBruta'].sum().sort_values(ascending=False)
print("\nProdutividade por terminal (CORRIGIDO DE VERDADE):")
print(produtividade)

# Converter para número
final['VLPesoCargaBruta'] = pd.to_numeric(final['VLPesoCargaBruta'], errors='coerce')

# Calcular a produtividade (carga por hora)
final['Carga_por_Hora'] = final['VLPesoCargaBruta'] / final['Tempo_operacao']

# Agrupar por terminal e tirar média
carga_hora_media = final.groupby('CDTUP')['Carga_por_Hora'].mean().sort_values(ascending=False)

print("Média de carga movimentada por hora de operação (por terminal):")
print(carga_hora_media)

## CORRETO QUESTÃO 1

import pandas as pd
import numpy as np

# Converte as colunas para números
final['VLPesoCargaBruta'] = pd.to_numeric(final['VLPesoCargaBruta'], errors='coerce')
final['Tempo_operacao'] = pd.to_numeric(final['Tempo_operacao'], errors='coerce')

# Remove linhas com dados faltando ou valores estranhos
final.dropna(subset=['VLPesoCargaBruta', 'Tempo_operacao'], inplace=True)

# Remove pesos absurdos (ex: acima de 1 milhão de toneladas) e tempos inválidos
final = final[(final['VLPesoCargaBruta'] > 0) & (final['VLPesoCargaBruta'] < 1e6)]
final = final[(final['Tempo_operacao'] > 0) & (final['Tempo_operacao'] < 1e6)]

# Calcula a produtividade
final['Carga_por_Hora'] = final['VLPesoCargaBruta'] / final['Tempo_operacao']

# Agrupa por terminal e tira média
carga_hora_media = final.groupby('CDTUP')['Carga_por_Hora'].mean().sort_values(ascending=False)

print("Média de carga movimentada por hora de operação (por terminal):")
print(carga_hora_media)

from google.colab import files
import pandas as pd

# Dicionário com seus DataFrames (substitua pelas suas variáveis reais)
dataframes_para_exportar = {
    "carga_hora_media": carga_hora_media
}

# Verificação e exportação
for nome_df, df in dataframes_para_exportar.items():
    try:
        # Verifica se é um DataFrame (ou Series, que também pode ser exportada)
        if isinstance(df, (pd.DataFrame, pd.Series)):
            nome_arquivo = f"{nome_df}.csv"

            # Converte Series para DataFrame se necessário
            if isinstance(df, pd.Series):
                df = df.to_frame()

            df.to_csv(nome_arquivo, index=True, encoding='utf-8-sig')  # index=True mantém os índices
            files.download(nome_arquivo)
            print(f"✅ {nome_df} exportado como {nome_arquivo}")
        else:
            print(f"⚠️ {nome_df} não é um DataFrame/Series (tipo: {type(df)})")
    except Exception as e:
        print(f"❌ Erro ao exportar {nome_df}: {str(e)}")

#TAREFA 3
# Importando as bibliotecas necessárias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Configurações para visualização mais bonita dos gráficos
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (15, 8)

# Carregando os dados
atracacao_2023 = pd.read_csv(file6, delimiter=';')
atracacao_2024 = pd.read_csv(file5, delimiter=';')
paralisacao_2023 = pd.read_csv(file8, delimiter=';')
paralisacao_2024 = pd.read_csv(file7, delimiter=';')

# Juntando os dados de paralisação
paralisacao = pd.concat([paralisacao_2023, paralisacao_2024], ignore_index=True)

# Convertendo datas para o formato datetime
paralisacao['DTInicio'] = pd.to_datetime(paralisacao['DTInicio'], dayfirst=True)
paralisacao['DTTermino'] = pd.to_datetime(paralisacao['DTTermino'], dayfirst=True)

# Calculando a duração das paralisações em horas
paralisacao['DuracaoHoras'] = (paralisacao['DTTermino'] - paralisacao['DTInicio']).dt.total_seconds() / 3600

# Extraindo mês e ano para análise sazonal
paralisacao['Mes'] = paralisacao['DTInicio'].dt.month
paralisacao['Ano'] = paralisacao['DTInicio'].dt.year

# Agrupando por motivo, mês e ano
top_motivos = paralisacao.groupby(['DescricaoTempoDesconto', 'Mes', 'Ano']).agg(
    Total_Horas=('DuracaoHoras', 'sum'),
    Total_Paradas=('IDTemposDescontos', 'count')
).reset_index()

top_motivos = top_motivos.sort_values(by='Total_Horas', ascending=False)

# Exibindo os Top 10 motivos com mais horas de paralisação
print(top_motivos.head(10))

# Criando um gráfico para visualizar os principais motivos
plt.figure(figsize=(15, 8))
sns.barplot(data=top_motivos.head(10), x='DescricaoTempoDesconto', y='Total_Horas', hue='Ano', dodge=True)
plt.title('Top 10 Motivos de Paradas Portuárias (2023-2024)', fontsize=20)
plt.xticks(rotation=45)
plt.ylabel('Total de Horas Paradas')
plt.xlabel('Motivo da Paralisação')
plt.show()

paralisacao_2023

#IMPRESSAO TAREFA 3 - 50%
from google.colab import files
import pandas as pd

# Dicionário com seus DataFrames (substitua pelas suas variáveis reais)
dataframes_para_exportar = {
    "top_motivos": top_motivos
}

# Verificação e exportação
for nome_df, df in dataframes_para_exportar.items():
    try:
        # Verifica se é um DataFrame (ou Series, que também pode ser exportada)
        if isinstance(df, (pd.DataFrame, pd.Series)):
            nome_arquivo = f"{nome_df}.csv"

            # Converte Series para DataFrame se necessário
            if isinstance(df, pd.Series):
                df = df.to_frame()

            df.to_csv(nome_arquivo, index=True, encoding='utf-8-sig')  # index=True mantém os índices
            files.download(nome_arquivo)
            print(f"✅ {nome_df} exportado como {nome_arquivo}")
        else:
            print(f"⚠️ {nome_df} não é um DataFrame/Series (tipo: {type(df)})")
    except Exception as e:
        print(f"❌ Erro ao exportar {nome_df}: {str(e)}")

print("\nTodos os arquivos exportados com sucesso!")

top_motivos

print(final.columns)

colunas_interesse = ['Porto Atracação', 'Complexo Portuário']
final_1 = final[colunas_interesse].dropna()

final_1

final_1 = final[['IDAtracacao', 'Porto Atracação', 'Complexo Portuário']].dropna().drop_duplicates()

paralisacao_local = paralisacao.merge(final_1, on='IDAtracacao', how='left')

paralisacao_local['Mes'] = paralisacao_local['DTInicio'].dt.month
paralisacao_local['Ano'] = paralisacao_local['DTInicio'].dt.year

top_motivos_com_local = paralisacao_local.groupby(['DescricaoTempoDesconto', 'Mes', 'Ano',
                                                    'Porto Atracação', 'Complexo Portuário', 'IDAtracacao']).agg(
    Total_Horas=('DuracaoHoras', 'sum'),
    Total_Paradas=('IDTemposDescontos', 'count')
).reset_index()

df_final = pd.merge(
    top_motivos_com_local,
    final_1.drop_duplicates(subset=['Porto Atracação', 'Complexo Portuário']),
    on=['Porto Atracação', 'Complexo Portuário'],
    how='left'  # ou 'inner' se quiser só os que existem nos dois
)

df_final

df_final.to_csv("top_motivos_com_local.csv", index=False, encoding='utf-8-sig')
files.download("top_motivos_com_local.csv")

